export interface Character {
  id: Number,
  image: String,
  name: String,
  sex: boolean,
  isYoung: boolean,
  isOld: boolean,
  isFat: boolean,
  isFit: boolean,
  isExecutive: boolean,
  isMedic: boolean,
  isHomeless: boolean,
  isCriminal: boolean,
  isHuman: boolean,
  isAnimal: boolean,
}
